# Generated by Django 5.0.3 on 2024-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.TextField(default=False),
        ),
    ]
