# Generated by Django 5.0.3 on 2024-05-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0006_remove_order_paid_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.TextField(default=None),
        ),
    ]
