# Generated by Django 5.0.3 on 2024-03-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0006_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='attribute_types',
        ),
        migrations.CreateModel(
            name='ProductCategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.productattributetype')),
                ('attributes', models.ManyToManyField(to='ecommerce_website.productattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.productcategory')),
            ],
        ),
    ]
