# Generated by Django 5.0.3 on 2024-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0007_remove_productcategory_attribute_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='active',
        ),
        migrations.AddField(
            model_name='productcategoryattribute',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
