# Generated by Django 5.0.3 on 2024-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0008_alter_order_payment_id_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
