# Generated by Django 5.0.3 on 2024-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0008_remove_productcategory_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
