# Generated by Django 5.0.3 on 2024-03-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0009_productcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce_website.productcategory'),
        ),
        migrations.DeleteModel(
            name='ProductCategoryAttribute',
        ),
    ]
