# Generated by Django 5.0.3 on 2024-05-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0009_storemotivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemotivation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storemotivation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
