# Generated by Django 5.0.3 on 2024-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0010_productcategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='attributes',
            field=models.ManyToManyField(related_name='categories', to='ecommerce_website.productattributetype'),
        ),
    ]
