# Generated by Django 5.0.3 on 2024-05-16 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0011_alter_productsale_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dealname', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('begin_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='active',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='dealname',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.sale'),
        ),
    ]
