# Generated by Django 5.0.3 on 2024-03-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0012_productcategory_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='attributes',
        ),
    ]
