# Generated by Django 5.0.3 on 2024-05-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0012_sale_remove_productsale_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='dealname',
        ),
    ]
