# Generated by Django 5.0.3 on 2024-05-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0013_remove_sale_dealname'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemotivation',
            name='for_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storemotivation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_motivation_images/'),
        ),
        migrations.AddField(
            model_name='storemotivation',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.sale'),
        ),
    ]
