# Generated by Django 5.0.3 on 2024-03-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0013_remove_productcategory_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.productcategory')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.productattribute')),
            ],
        ),
    ]
