# Generated by Django 5.0.3 on 2024-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0014_productfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilter',
            name='product_attribute',
        ),
        migrations.AddField(
            model_name='productfilter',
            name='product_attributes',
            field=models.ManyToManyField(to='ecommerce_website.productattribute'),
        ),
    ]
