# Generated by Django 5.0.3 on 2024-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0014_storemotivation_for_homepage_storemotivation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_days', models.DecimalField(decimal_places=0, default=9, max_digits=2)),
            ],
        ),
    ]
