# Generated by Django 5.0.3 on 2024-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0015_remove_productfilter_product_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
    ]
