# Generated by Django 5.0.3 on 2024-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0015_deliverymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
