# Generated by Django 5.0.3 on 2024-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0016_deliverymethod_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
