# Generated by Django 5.0.3 on 2024-03-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0017_orderline_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='price',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='ecommerce_website.order'),
        ),
    ]
