# Generated by Django 5.0.3 on 2024-05-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0019_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='for_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
