# Generated by Django 5.0.3 on 2024-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0020_rename_price_order_tax_price_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
