# Generated by Django 5.0.3 on 2024-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0021_order_sub_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='runner',
            field=models.BooleanField(default=False),
        ),
    ]
