# Generated by Django 5.0.3 on 2024-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0022_returnorder_orderline_return_order_returnorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.TextField(default='Openstaand'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('pending', 'Pending'), ('failed', 'Failed')], default='requested', max_length=20),
        ),
    ]
