# Generated by Django 5.0.3 on 2024-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0023_order_order_status_alter_returnorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'Open'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='Open'),
        ),
    ]
