# Generated by Django 5.0.3 on 2024-04-03 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0023_alter_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dealname', models.CharField(max_length=100)),
                ('begin_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product')),
            ],
        ),
    ]
