# Generated by Django 5.0.3 on 2024-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0024_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='category_thumbnails/'),
        ),
    ]
