# Generated by Django 5.0.3 on 2024-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0024_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'Openstaand'), ('paid', 'Betaald'), ('delivered', 'Geleverd')], default='Openstaand'),
        ),
    ]
