# Generated by Django 5.0.3 on 2024-04-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0025_productcategory_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='runner',
        ),
    ]
