# Generated by Django 5.0.3 on 2024-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0025_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
