# Generated by Django 5.0.3 on 2024-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0026_remove_product_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='runner',
            field=models.BooleanField(default=False),
        ),
    ]
