# Generated by Django 5.0.3 on 2024-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0026_order_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_information_id',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'Openstaand'), ('paid', 'Betaald'), ('delivered', 'Geleverd'), ('failed', 'Mislukt')], default='Openstaand'),
        ),
    ]
