# Generated by Django 5.0.3 on 2024-04-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0027_product_runner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
