# Generated by Django 5.0.3 on 2024-06-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0027_order_payment_information_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_issuer',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
