# Generated by Django 5.0.3 on 2024-04-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0028_alter_productattributetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.productcategory'),
        ),
    ]
