# Generated by Django 5.0.3 on 2024-06-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0028_order_payment_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='ecommerce_website.product')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_to', to='ecommerce_website.product')),
            ],
        ),
    ]
