# Generated by Django 5.0.3 on 2024-06-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0029_relatedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedproduct',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='ecommerce_website.product'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='related_products',
            field=models.ManyToManyField(related_name='related_products', to='ecommerce_website.product'),
        ),
    ]
