# Generated by Django 5.0.3 on 2024-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0029_alter_productfilter_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
