# Generated by Django 5.0.3 on 2024-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0030_product_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='margin',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
