# Generated by Django 5.0.3 on 2024-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0031_remove_product_margin_product_selling_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
