# Generated by Django 5.0.3 on 2024-08-18 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0031_storerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
