# Generated by Django 5.0.3 on 2024-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0032_alter_storerating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='for_category_section',
            field=models.BooleanField(default=False),
        ),
    ]
