# Generated by Django 5.0.3 on 2024-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0033_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(db_index=True, decimal_places=2, default=9.0, max_digits=5),
        ),
    ]
