# Generated by Django 5.0.3 on 2024-08-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0033_productcategory_for_category_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedProduct',
        ),
    ]
