# Generated by Django 5.0.3 on 2024-08-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0034_delete_relatedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='for_category_section',
        ),
    ]
