# Generated by Django 5.0.3 on 2024-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0035_remove_productcategory_for_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
        ),
    ]
