# Generated by Django 5.0.3 on 2024-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0036_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilter',
            name='product_attributes',
        ),
        migrations.AddField(
            model_name='productfilter',
            name='filter_type',
            field=models.CharField(choices=[('string', 'String'), ('slider', 'Slider')], default='string', max_length=10),
        ),
        migrations.AddField(
            model_name='productfilter',
            name='values',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
