# Generated by Django 5.0.3 on 2024-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0037_remove_productfilter_product_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='filter_type',
            field=models.CharField(choices=[('option', 'Option'), ('slider', 'Slider')], default='option', max_length=10),
        ),
    ]
