# Generated by Django 5.0.3 on 2024-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0038_alter_productfilter_filter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salutation',
            field=models.CharField(default='Geen van beiden', max_length=100),
        ),
    ]
