# Generated by Django 5.0.3 on 2024-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0039_order_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
