# Generated by Django 5.0.3 on 2024-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0040_productattribute_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='numeric_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=10, default=None, max_digits=20, null=True),
        ),
    ]
