# Generated by Django 5.0.3 on 2024-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0041_productattribute_numeric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='numeric_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
