# Generated by Django 5.0.3 on 2024-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0042_alter_productattribute_numeric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='unit_value',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
