# Generated by Django 5.0.3 on 2024-12-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0043_productfilter_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='count_delivered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
