# Generated by Django 5.0.3 on 2024-12-13 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0045_returnorder_address_returnorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
