# Generated by Django 5.0.3 on 2024-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0046_returnorder_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('takeaway', 'Takeaway')], default='delivery', max_length=10),
        ),
    ]
