# Generated by Django 5.0.3 on 2024-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0047_deliverymethod_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
