# Generated by Django 5.0.3 on 2024-12-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0048_deliverymethod_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='deliver_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='deliver_method',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='payment_information',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='payment_information_id',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='payment_issuer',
            field=models.TextField(default=None, max_length=20, null=True),
        ),
    ]
