# Generated by Django 5.0.3 on 2024-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0049_returnorder_deliver_date_returnorder_deliver_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='deliver_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='deliver_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='payment_information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='payment_information_id',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='payment_issuer',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
