# Generated by Django 5.0.3 on 2024-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0050_alter_returnorder_deliver_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='payment_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='payment_url',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
