# Generated by Django 5.0.3 on 2024-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0051_returnorder_payment_id_returnorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorderline',
            name='count_delivered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='returnorderline',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('open', 'Openstaand'), ('paid', 'Betaald'), ('delivered', 'Geleverd'), ('failed', 'Mislukt')], default='open', max_length=20),
        ),
    ]
