# Generated by Django 5.0.3 on 2024-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0052_returnorderline_count_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='sub_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_price_high',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='tax_price_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'Openstaand'), ('paid', 'Betaald'), ('delivered', 'Geleverd'), ('partly', 'Deels geleverd'), ('failed', 'Mislukt')], default='open'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('open', 'Openstaand'), ('paid', 'Betaald'), ('delivered', 'Opgehaald'), ('partly', 'Deels opgehaald'), ('failed', 'Mislukt'), ('done', 'Afgerond')], default='open', max_length=20),
        ),
    ]
