# Generated by Django 5.0.3 on 2024-12-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0053_returnorder_sub_price_returnorder_tax_price_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='returnorder',
            name='billing_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorder',
            name='shipping_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(db_index=True, decimal_places=2, default=21, max_digits=5),
        ),
    ]
