# Generated by Django 5.0.3 on 2024-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0054_remove_returnorder_address_remove_returnorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='socials',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
