# Generated by Django 5.0.3 on 2024-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0055_store_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='faq',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
