# Generated by Django 5.0.3 on 2024-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0056_store_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='Goedkoopstevloerenshop.nl', max_length=20),
            preserve_default=False,
        ),
    ]
