# Generated by Django 5.0.3 on 2024-12-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0058_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemotivation',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
