# Generated by Django 5.0.3 on 2024-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0059_storemotivation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(default='Nu openingssale tot wel 30% korting op vloeren!', max_length=100),
            preserve_default=False,
        ),
    ]
