# Generated by Django 5.0.3 on 2024-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0060_sale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='0643774343', max_length=20),
            preserve_default=False,
        ),
    ]
