# Generated by Django 5.0.3 on 2024-12-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0063_remove_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
