# Generated by Django 5.0.3 on 2024-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0064_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
