# Generated by Django 5.0.3 on 2024-12-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0065_returnorder_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price',
        ),
    ]
