# Generated by Django 5.0.3 on 2024-12-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0066_remove_orderline_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
