# Generated by Django 5.0.3 on 2025-01-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0067_orderline_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
