# Generated by Django 5.0.3 on 2025-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0074_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
