# Generated by Django 5.0.3 on 2025-01-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0076_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
