# Generated by Django 5.0.3 on 2025-01-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0077_product_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_url',
        ),
    ]
