# Generated by Django 5.0.3 on 2025-01-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0078_remove_product_thumbnail_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productfilter',
            unique_together={('name', 'parent_category')},
        ),
    ]
