# Generated by Django 5.0.3 on 2025-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0081_remove_product_thumbnail_alter_product_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
