# Generated by Django 5.0.3 on 2025-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0083_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemotivation',
            name='sort_order',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
