# Generated by Django 5.0.3 on 2025-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0084_storemotivation_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemotivation',
            name='image',
        ),
    ]
