# Generated by Django 5.0.3 on 2025-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0085_remove_storemotivation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
